### ISSUE TITLE
Detect when user changes metamask account

### ISSUE THREAD

**Issue by sylvieaaa** [teampepe69/cryptomeme#35]
reproduce steps:

- User signs in with account[1]'s private key via the metamask (approve it first using admin account)
- User switches metamask back to account[0] )(admin) while still logged in as account[1]

**Expected result:**
Dapp should log user out of account[1], and user would need to re log-in again as admin account

**Actual result:**
No change, the dapp still registers the user as being logged in with account[1]

**Comment by quentinkhoo** [comment]
How to fix? D:

**Comment by TzeMeng** [comment]
is there a hook in REACT that will run when the state is changed? or another costly way to implement it will be comparing the ewallet from metamask to the contract on every action?
